language: java
script:
  -  mvn clean test
after_success:
  -  test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && mvn deploy -DskipTests=true --settings maven_deploy_settings.xml
jdk:
- oraclejdk8
env:
  global:
  - secure: F0DzBlxI0sDo3osFcfgGCjrX3HQeMWqJBF42/Pg0UE1UIgAUoMq8hrl7OegZPCo8ymg55CNxGaAcqNSQTeAyuXOh1G+Eokkh9UPyT+PpZFLLBT+0LZdbl4w7jhqBHGrHn9F6a4uiVbuLtWj9pyOVjcdwhsRAmOik76ZDvF0Mo2o=
  - secure: bN0Vj5bk8UAIhoOyeG1DsNgcWOfVGvgUWU4g8T9a2XJayQIirD16NbXxImAClnlE0yMHVwvw0vrrp5Em/Z0y95QO3qIbEi7sirVpRjpIi2h5nRl9O1wcSe+iXdXURKExzBT4Pfl/UrMaYzgwIKjBSz29z6MPkrWiGz4GsnFufOk=
